# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

# 触发时机，在 main 分支 push 操作触发
on:
  push:
    branches:
      - main

# 默认shell
defaults:
  run:
    shell: bash

# 任务，定义个changelog 的任务
jobs:
  changelog:
    # name:Changelog PR or Release
    runs-on: ubuntu-latest
    steps:
      # name:  当前 step 的名字
      - name: Checkout # 获取分支的代码和提交记录
        uses: actions/checkout@v3

      # 设置 Node
      - name: Setup Node.js # 设置 Node.js 的环境
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          # cache: 'npm'

      # 安装依赖
      - name: Install dependencies
        run: npm install

      # 打包
      - name: Build Packages
        run: npm run build

      # ci
      - name: run ci
        run: npm ci

      # publish
      - name: run publish
        run: npm publish
        env:
          # 这里需要几个 Token 变量
          # GITHUB_TOKEN 是 CI 里自带的默认 token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NPM_TOKEN 需要稍后在 npm 网站生成。
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
