name: Publish Package to npmjs

on:
  push:
    branches: [ main ]

env:
  NODE_VERSION: 18
  GITHUB_REGISTRY_URL: 'https://npm.pkg.github.com/'
  NPM_REGISTRY_URL: 'https://registry.npmjs.org'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Setup Node.js and publish to GitHub Package Registry
        uses: actions/setup-node@v4
        with:
          registry-url: ${{ env.GITHUB_REGISTRY_URL }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js and publish to npm
        uses: actions/setup-node@v4
        with:
          registry-url: ${{ env.NPM_REGISTRY_URL }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
  release:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch  # 默认为 patch，你也可以选择 minor 或 major

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub 提供的 token
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}  # 使用上一步生成的 tag
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}  # Release 名称
          draft: false
          prerelease: false
